import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const fontSans = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={["font-mono", fontSans.variable].join(" ")}>
      <body className="bg-white flex flex-col min-h-screen">{children}</body>
    </html>
  )
}
